# Generated by Django 2.2.2 on 2019-07-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0006_pool_passenger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
            preserve_default=False,
        ),
    ]
