# Generated by Django 2.2.2 on 2019-07-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0007_auto_20190702_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='passenger',
            field=models.CharField(max_length=100),
        ),
    ]
