# Generated by Django 2.2.2 on 2019-07-03 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0009_remove_pool_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Номер телефона должен быть введен в формате: '+79149999999'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
