# Generated by Django 2.2.2 on 2019-07-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0010_pool_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
    ]
