# Generated by Django 2.2.2 on 2019-07-03 09:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0013_auto_20190703_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
    ]
