# Generated by Django 2.2.2 on 2019-07-03 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0014_pool_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='note',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
