# Generated by Django 2.2.2 on 2019-07-03 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0015_pool_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
