# Generated by Django 2.2.2 on 2019-07-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0016_auto_20190703_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pool',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
