# Generated by Django 2.2.2 on 2019-07-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0017_auto_20190705_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='slots',
        ),
        migrations.AlterField(
            model_name='pool',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
