# Generated by Django 2.2.2 on 2019-07-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0018_auto_20190705_1400'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='amount',
        ),
    ]
