# Generated by Django 2.2.2 on 2019-07-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0020_auto_20190705_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='pool',
            name='last_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='pool',
            name='passenger',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
