# Generated by Django 2.2.2 on 2019-07-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0021_auto_20190705_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='vk_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
